apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: kind-skaffold
build:
  artifacts:
  - image: kind-skaffold
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
portForward:
  - resourceType: service
    resourceName: server
    port: 8080
    localPort: 8080